Bump dependencies 161224
navikt/navno-search-frontend pull request #177
Opened 2024-12-16 15:01 UTC by eivindskifjeld

## Oppsummering av hva som er gjort

Oppdatert avhengigheter.

Ingen større oppdateringer, bortsett fra eslint-config-next: 14.2.15 --> 15.1.0

Se  også dependenciesComments.

## Testing

Har testet i dev.

2024-12-16 15:28 UTC, terjeofnorway requested changes

2024-12-16 15:28 UTC, terjeofnorway commented on package.json
> +        "eslint-config-next": "15.1.0",
Bør vi holde denne til 14x frem til vi oppgraderer Next?

2024-12-17 08:23 UTC, eivindskifjeld commented on package.json
> +        "eslint-config-next": "15.1.0",
Jeg hadde til og med skrevet i kommentarene at den skal holdes på versjon 14.2.5.

"next": "Holdes på versjon 14.2.15 --> 15.1.0"

Takk for at du la merke til den!

2025-01-10 11:47 UTC, closed without merging

2025-01-10 11:47 UTC, eivindskifjeld commented
Gammel. Erstattes av en ny.